### ISSUE TITLE
Use shiftplanning API instead of scraping 

### ISSUE THREAD

**Issue by mikaellindemann** [AnalogIO/CafeAnalogAndroid#3]
The title says it all. 
Alternatively wait for the asp.net api to mature and release

**Comment by Hanspagh** [comment]
May I suggest using something like [Retrofit](http://square.github.io/retrofit/) to simplify the networking part of the application

**Comment by xthedeus** [comment]
Or [Volley by Google](http://developer.android.com/training/volley/index.html)

**Comment by mikaellindemann** [comment]
It has been implemented by the use of standard Java APIs for now. Retrofit looks cool though. Please don't hesitate to jump into the development ☺️
